[project]
name = "group13-softsec"
version = "0.1.0"
dependencies = [
    "flask",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[tool.ruff]
line-length = 88
target-version = "py312"


# E: pycodestyle errors e.g., whitespace, line length, indentation, trailing spaces)
# F: Pyflakes, logical and syntax errors without running the code (e.g., unused imports/variables, undefined names, duplicate keys)
# I: isort, the import sorting and categorization in alphabetical order
[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
pythonpath = ["."]
